server:
  port: 8081
tomcat:
  max-http-post-size: 8192

spring:
  profiles:
    # 外置jdbc、redis和mail配置文件
    active: jdbc,redis,mail
  # 关闭thymeleaf页面缓存
  thymeleaf:
    cache: false
  # 配置国际化资源文件
  messages:
    basename: i18n.logo
  main:
    allow-circular-references: true

# MyBatis配置
mybatis:
  configuration:
    #开启驼峰命名匹配映射
    map-underscore-to-camel-case: true

#pagehelper分页设置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#浏览器cookie相关设置
COOKIE:
  # 设置cookie默认时长为30分钟
  VALIDITY: 1800


